### ISSUE TITLE
Support queries longer than 4KB

### ISSUE THREAD

**Issue by yuekselba** [JohannesOehm/FhirExtinguisher#12]
Currently, queries are processed from HTTP-GET requests. This limits the longest possible Request to the longest URI the application accepts. This currently is roughly about 4KB. 
Is it possible to circumvent this limitation? For example, implementing a HTTP-POST endpoint where the query is transmitted as body data could help.

Thank you very much.

**Comment by JohannesOehm** [comment]
Hi there :) 

Are you using the frontend or are you using the REST endpoint directly?

If the request is longer, the frontend should use a HTTP-POST-Request instead of GET to submit the FHIR Search query + the FHIRPath selectors. It uses a `POST /fhir/<FHIR-SEARCH-QUERY>` with `__column` and `__limit` parameters in the body of the request. However, GET is always used to retrieve the data from the FHIR server. In theory, with a very long FHIR Search query, you could break things.

The frontend triggers the browsers download function by internally creating a `form[action=POST]` with the `__column` and `__limit` parameters and triggering the submission via javascript. Which browser are you using?

**Comment by yuekselba** [comment]
Thanks, I didn't know that the POST already is implemented. That really does the trick. Sorry for the noise!
